#Application Configuration
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
# ===============================
# DB
# ===============================
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://b281a7a6cf7fca:02913f73@us-cdbr-east-02.cleardb.com/heroku_948a42d3a5ec63a?reconnect=true
    username: b281a7a6cf7fca
    password: 02913f73
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://52.147.213.77:8099/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
