#Application Configuration
server:
  port: 8094
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://bb210307cbff1a:1f62a7f2@us-cdbr-east-02.cleardb.com/heroku_66f266cb39a1008?reconnect=true
    username: bb210307cbff1a
    password: 1f62a7f2
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://52.147.213.77:8099/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
