#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8093/h2-console
# Enabling H2 Console
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://b3b9dd314422d2:92517cd2@us-cdbr-east-02.cleardb.com/heroku_d75c3019c011dab?reconnect=true
    username: b3b9dd314422d2
    password: 92517cd2
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://52.147.213.77:8099/eureka/
# Feign and Hystrix
Feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
